
#include "WinMaliKmd.h"
#include "WinMaliDxgkInitFill.h"
#include "WinMaliDxgkStubs.h"

VOID
WinMaliDxgkPatchInitializationData(_Out_ DRIVER_INITIALIZATION_DATA* init)
{
    RtlZeroMemory(init, sizeof(*init));

    /* We compile against the 26100 WDK -> DXGKDDI_INTERFACE_VERSION is
       DXGKDDI_INTERFACE_VERSION_WDDM3_2 (0x11007). dxgkrnl validates
       every field the struct exposes at the declared version: a NULL
       callback dxgk considers mandatory at that version is rejected
       with STATUS_REVISION_MISMATCH (DxgKrnl-Admin event 549,
       StartAdapter_AddAdapterFailed). Win11 24H2 also refuses to
       register a NEW third-party adapter that declares WDDM 2.5, so
       pinning an older version is not an escape hatch - we must claim
       3.2 and wire the whole struct.

       Strategy: real implementations where we have them, logging stubs
       for the rest, NULL for the display/VidPN/overlay/flip-queue set
       (NULL is the "capability absent" signal for a render-only
       adapter - a stub there is a false claim dxgk acts on).

       The wire-up block below is generated by Tools\gen-dxgk-stubs.py
       from the DRIVER_INITIALIZATION_DATA definition in the WDK's
       dispmprt.h. Re-run that script after any WDK upgrade. */

    /* DRIVERCAPS.WDDMVersion in WinMaliQai.c reports DXGKDDI_WDDMv3_2
       to match this (both must align or dxgkrnl rejects the adapter
       at DriverInitialize / AddAdapter time). */
    init->Version = DXGKDDI_INTERFACE_VERSION;

#include "WinMaliDxgkStubsWire.h"
}
