// AUTO-GENERATED by Tools/gen_d3d11_devstubs.py — do not edit by hand.
// Compiled as C++ (MSVC C disallows unnamed parameters in stub definitions).
// Source SDK header: C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\um\d3d10umddi.h
#include "WinMaliUmd.h"
#include <cstring>

static VOID APIENTRY _wm_stub_0_pfnDefaultConstantBufferUpdateSubresourceUP(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT, CONST D3D10_DDI_BOX*, CONST VOID*, UINT, UINT) { (void)0; }
static VOID APIENTRY _wm_stub_1_pfnVsSetConstantBuffers(D3D10DDI_HDEVICE, UINT StartSlot, UINT NumBuffers, CONST D3D10DDI_HRESOURCE*) { (void)0; }
static VOID APIENTRY _wm_stub_2_pfnPsSetShaderResources(D3D10DDI_HDEVICE, UINT StartSlot, UINT NumViews, CONST D3D10DDI_HSHADERRESOURCEVIEW*) { (void)0; }
static VOID APIENTRY _wm_stub_3_pfnPsSetShader(D3D10DDI_HDEVICE, D3D10DDI_HSHADER) { (void)0; }
static VOID APIENTRY _wm_stub_4_pfnPsSetSamplers(D3D10DDI_HDEVICE, UINT StartSlot, UINT NumSamplers, CONST D3D10DDI_HSAMPLER*) { (void)0; }
static VOID APIENTRY _wm_stub_5_pfnVsSetShader(D3D10DDI_HDEVICE, D3D10DDI_HSHADER) { (void)0; }
static VOID APIENTRY _wm_stub_6_pfnDrawIndexed(D3D10DDI_HDEVICE, UINT, UINT, INT) { (void)0; }
static VOID APIENTRY _wm_stub_7_pfnDraw(D3D10DDI_HDEVICE, UINT, UINT) { (void)0; }
static VOID APIENTRY _wm_stub_8_pfnDynamicIABufferMapNoOverwrite(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT, D3D10_DDI_MAP, UINT, D3D10DDI_MAPPED_SUBRESOURCE*) { (void)0; }
static VOID APIENTRY _wm_stub_9_pfnDynamicIABufferUnmap(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT) { (void)0; }
static VOID APIENTRY _wm_stub_10_pfnDynamicConstantBufferMapDiscard(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT, D3D10_DDI_MAP, UINT, D3D10DDI_MAPPED_SUBRESOURCE*) { (void)0; }
static VOID APIENTRY _wm_stub_11_pfnDynamicIABufferMapDiscard(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT, D3D10_DDI_MAP, UINT, D3D10DDI_MAPPED_SUBRESOURCE*) { (void)0; }
static VOID APIENTRY _wm_stub_12_pfnDynamicConstantBufferUnmap(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT) { (void)0; }
static VOID APIENTRY _wm_stub_13_pfnPsSetConstantBuffers(D3D10DDI_HDEVICE, UINT StartSlot, UINT NumBuffers, CONST D3D10DDI_HRESOURCE*) { (void)0; }
static VOID APIENTRY _wm_stub_14_pfnIaSetInputLayout(D3D10DDI_HDEVICE, D3D10DDI_HELEMENTLAYOUT) { (void)0; }
static VOID APIENTRY _wm_stub_15_pfnIaSetVertexBuffers(D3D10DDI_HDEVICE, UINT StartSlot, UINT NumBuffers, CONST D3D10DDI_HRESOURCE*, CONST UINT*, CONST UINT*) { (void)0; }
static VOID APIENTRY _wm_stub_16_pfnIaSetIndexBuffer(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, DXGI_FORMAT, UINT) { (void)0; }
static VOID APIENTRY _wm_stub_17_pfnDrawIndexedInstanced(D3D10DDI_HDEVICE, UINT, UINT, UINT, INT, UINT) { (void)0; }
static VOID APIENTRY _wm_stub_18_pfnDrawInstanced(D3D10DDI_HDEVICE, UINT, UINT, UINT, UINT) { (void)0; }
static VOID APIENTRY _wm_stub_19_pfnDynamicResourceMapDiscard(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT, D3D10_DDI_MAP, UINT, D3D10DDI_MAPPED_SUBRESOURCE*) { (void)0; }
static VOID APIENTRY _wm_stub_20_pfnDynamicResourceUnmap(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT) { (void)0; }
static VOID APIENTRY _wm_stub_21_pfnGsSetConstantBuffers(D3D10DDI_HDEVICE, UINT StartSlot, UINT NumBuffers, CONST D3D10DDI_HRESOURCE*) { (void)0; }
static VOID APIENTRY _wm_stub_22_pfnGsSetShader(D3D10DDI_HDEVICE, D3D10DDI_HSHADER) { (void)0; }
static VOID APIENTRY _wm_stub_23_pfnIaSetTopology(D3D10DDI_HDEVICE, D3D10_DDI_PRIMITIVE_TOPOLOGY) { (void)0; }
static VOID APIENTRY _wm_stub_24_pfnStagingResourceMap(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT, D3D10_DDI_MAP, UINT, D3D10DDI_MAPPED_SUBRESOURCE*) { (void)0; }
static VOID APIENTRY _wm_stub_25_pfnStagingResourceUnmap(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT) { (void)0; }
static VOID APIENTRY _wm_stub_26_pfnVsSetShaderResources(D3D10DDI_HDEVICE, UINT StartSlot, UINT NumViews, CONST D3D10DDI_HSHADERRESOURCEVIEW*) { (void)0; }
static VOID APIENTRY _wm_stub_27_pfnVsSetSamplers(D3D10DDI_HDEVICE, UINT StartSlot, UINT NumSamplers, CONST D3D10DDI_HSAMPLER*) { (void)0; }
static VOID APIENTRY _wm_stub_28_pfnGsSetShaderResources(D3D10DDI_HDEVICE, UINT StartSlot, UINT NumViews, CONST D3D10DDI_HSHADERRESOURCEVIEW*) { (void)0; }
static VOID APIENTRY _wm_stub_29_pfnGsSetSamplers(D3D10DDI_HDEVICE, UINT StartSlot, UINT NumSamplers, CONST D3D10DDI_HSAMPLER*) { (void)0; }
static VOID APIENTRY _wm_stub_30_pfnSetRenderTargets(D3D10DDI_HDEVICE, CONST D3D10DDI_HRENDERTARGETVIEW*, UINT NumRTVs, UINT ClearSlots, D3D10DDI_HDEPTHSTENCILVIEW, CONST D3D11DDI_HUNORDEREDACCESSVIEW*, CONST UINT*, UINT UAVStartSlot, UINT NumUAVs, UINT UAVRangeStart, UINT UAVRangeSize) { (void)0; }
static VOID APIENTRY _wm_stub_31_pfnShaderResourceViewReadAfterWriteHazard(D3D10DDI_HDEVICE, D3D10DDI_HSHADERRESOURCEVIEW, D3D10DDI_HRESOURCE) { (void)0; }
static VOID APIENTRY _wm_stub_32_pfnResourceReadAfterWriteHazard(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE) { (void)0; }
static VOID APIENTRY _wm_stub_33_pfnSetBlendState(D3D10DDI_HDEVICE, D3D10DDI_HBLENDSTATE, CONST FLOAT[4], UINT) { (void)0; }
static VOID APIENTRY _wm_stub_34_pfnSetDepthStencilState(D3D10DDI_HDEVICE, D3D10DDI_HDEPTHSTENCILSTATE, UINT) { (void)0; }
static VOID APIENTRY _wm_stub_35_pfnSetRasterizerState(D3D10DDI_HDEVICE, D3D10DDI_HRASTERIZERSTATE) { (void)0; }
static VOID APIENTRY _wm_stub_36_pfnQueryEnd(D3D10DDI_HDEVICE, D3D10DDI_HQUERY) { (void)0; }
static VOID APIENTRY _wm_stub_37_pfnQueryBegin(D3D10DDI_HDEVICE, D3D10DDI_HQUERY) { (void)0; }
static VOID APIENTRY _wm_stub_38_pfnResourceCopyRegion(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT, UINT, UINT, UINT, D3D10DDI_HRESOURCE, UINT, CONST D3D10_DDI_BOX*) { (void)0; }
static VOID APIENTRY _wm_stub_39_pfnResourceUpdateSubresourceUP(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT, CONST D3D10_DDI_BOX*, CONST VOID*, UINT, UINT) { (void)0; }
static VOID APIENTRY _wm_stub_40_pfnSoSetTargets(D3D10DDI_HDEVICE, UINT NumBuffers, UINT ClearTargets, CONST D3D10DDI_HRESOURCE*, CONST UINT*) { (void)0; }
static VOID APIENTRY _wm_stub_41_pfnDrawAuto(D3D10DDI_HDEVICE) { (void)0; }
static VOID APIENTRY _wm_stub_42_pfnSetViewports(D3D10DDI_HDEVICE, UINT NumViewports, UINT ClearViewports, CONST D3D10_DDI_VIEWPORT*) { (void)0; }
static VOID APIENTRY _wm_stub_43_pfnSetScissorRects(D3D10DDI_HDEVICE, UINT NumRects, UINT ClearRects, CONST D3D10_DDI_RECT*) { (void)0; }
static VOID APIENTRY _wm_stub_44_pfnClearRenderTargetView(D3D10DDI_HDEVICE, D3D10DDI_HRENDERTARGETVIEW, FLOAT[4]) { (void)0; }
static VOID APIENTRY _wm_stub_45_pfnClearDepthStencilView(D3D10DDI_HDEVICE, D3D10DDI_HDEPTHSTENCILVIEW, UINT, FLOAT, UINT8) { (void)0; }
static VOID APIENTRY _wm_stub_46_pfnSetPredication(D3D10DDI_HDEVICE, D3D10DDI_HQUERY, BOOL) { (void)0; }
static VOID APIENTRY _wm_stub_47_pfnQueryGetData(D3D10DDI_HDEVICE, D3D10DDI_HQUERY, VOID*, UINT DataSize, UINT) { (void)0; }
static VOID APIENTRY _wm_stub_48_pfnFlush(D3D10DDI_HDEVICE) { (void)0; }
static VOID APIENTRY _wm_stub_49_pfnGenMips(D3D10DDI_HDEVICE, D3D10DDI_HSHADERRESOURCEVIEW) { (void)0; }
static VOID APIENTRY _wm_stub_50_pfnResourceCopy(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, D3D10DDI_HRESOURCE) { (void)0; }
static VOID APIENTRY _wm_stub_51_pfnResourceResolveSubresource(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT, D3D10DDI_HRESOURCE, UINT, DXGI_FORMAT) { (void)0; }
static VOID APIENTRY _wm_stub_52_pfnResourceMap(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT, D3D10_DDI_MAP, UINT, D3D10DDI_MAPPED_SUBRESOURCE*) { (void)0; }
static VOID APIENTRY _wm_stub_53_pfnResourceUnmap(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT) { (void)0; }
static BOOL APIENTRY _wm_stub_54_pfnResourceIsStagingBusy(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE) { return 0; }
static VOID APIENTRY _wm_stub_55_pfnRelocateDeviceFuncs(D3D10DDI_HDEVICE, struct D3D11DDI_DEVICEFUNCS*) { (void)0; }
static SIZE_T APIENTRY _wm_stub_56_pfnCalcPrivateResourceSize(D3D10DDI_HDEVICE, CONST D3D11DDIARG_CREATERESOURCE*) { return 0; }
static SIZE_T APIENTRY _wm_stub_57_pfnCalcPrivateOpenedResourceSize(D3D10DDI_HDEVICE, CONST D3D10DDIARG_OPENRESOURCE*) { return 0; }
static VOID APIENTRY _wm_stub_58_pfnCreateResource(D3D10DDI_HDEVICE, CONST D3D11DDIARG_CREATERESOURCE*, D3D10DDI_HRESOURCE, D3D10DDI_HRTRESOURCE) { (void)0; }
static VOID APIENTRY _wm_stub_59_pfnOpenResource(D3D10DDI_HDEVICE, CONST D3D10DDIARG_OPENRESOURCE*, D3D10DDI_HRESOURCE, D3D10DDI_HRTRESOURCE) { (void)0; }
static VOID APIENTRY _wm_stub_60_pfnDestroyResource(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE) { (void)0; }
static SIZE_T APIENTRY _wm_stub_61_pfnCalcPrivateShaderResourceViewSize(D3D10DDI_HDEVICE, CONST D3D11DDIARG_CREATESHADERRESOURCEVIEW*) { return 0; }
static VOID APIENTRY _wm_stub_62_pfnCreateShaderResourceView(D3D10DDI_HDEVICE, CONST D3D11DDIARG_CREATESHADERRESOURCEVIEW*, D3D10DDI_HSHADERRESOURCEVIEW, D3D10DDI_HRTSHADERRESOURCEVIEW) { (void)0; }
static VOID APIENTRY _wm_stub_63_pfnDestroyShaderResourceView(D3D10DDI_HDEVICE, D3D10DDI_HSHADERRESOURCEVIEW) { (void)0; }
static SIZE_T APIENTRY _wm_stub_64_pfnCalcPrivateRenderTargetViewSize(D3D10DDI_HDEVICE, CONST D3D10DDIARG_CREATERENDERTARGETVIEW*) { return 0; }
static VOID APIENTRY _wm_stub_65_pfnCreateRenderTargetView(D3D10DDI_HDEVICE, CONST D3D10DDIARG_CREATERENDERTARGETVIEW*, D3D10DDI_HRENDERTARGETVIEW, D3D10DDI_HRTRENDERTARGETVIEW) { (void)0; }
static VOID APIENTRY _wm_stub_66_pfnDestroyRenderTargetView(D3D10DDI_HDEVICE, D3D10DDI_HRENDERTARGETVIEW) { (void)0; }
static SIZE_T APIENTRY _wm_stub_67_pfnCalcPrivateDepthStencilViewSize(D3D10DDI_HDEVICE, CONST D3D11DDIARG_CREATEDEPTHSTENCILVIEW*) { return 0; }
static VOID APIENTRY _wm_stub_68_pfnCreateDepthStencilView(D3D10DDI_HDEVICE, CONST D3D11DDIARG_CREATEDEPTHSTENCILVIEW*, D3D10DDI_HDEPTHSTENCILVIEW, D3D10DDI_HRTDEPTHSTENCILVIEW) { (void)0; }
static VOID APIENTRY _wm_stub_69_pfnDestroyDepthStencilView(D3D10DDI_HDEVICE, D3D10DDI_HDEPTHSTENCILVIEW) { (void)0; }
static SIZE_T APIENTRY _wm_stub_70_pfnCalcPrivateElementLayoutSize(D3D10DDI_HDEVICE, CONST D3D10DDIARG_CREATEELEMENTLAYOUT*) { return 0; }
static VOID APIENTRY _wm_stub_71_pfnCreateElementLayout(D3D10DDI_HDEVICE, CONST D3D10DDIARG_CREATEELEMENTLAYOUT*, D3D10DDI_HELEMENTLAYOUT, D3D10DDI_HRTELEMENTLAYOUT) { (void)0; }
static VOID APIENTRY _wm_stub_72_pfnDestroyElementLayout(D3D10DDI_HDEVICE, D3D10DDI_HELEMENTLAYOUT) { (void)0; }
static SIZE_T APIENTRY _wm_stub_73_pfnCalcPrivateBlendStateSize(D3D10DDI_HDEVICE, CONST D3D10_1_DDI_BLEND_DESC*) { return 0; }
static VOID APIENTRY _wm_stub_74_pfnCreateBlendState(D3D10DDI_HDEVICE, CONST D3D10_1_DDI_BLEND_DESC*, D3D10DDI_HBLENDSTATE, D3D10DDI_HRTBLENDSTATE) { (void)0; }
static VOID APIENTRY _wm_stub_75_pfnDestroyBlendState(D3D10DDI_HDEVICE, D3D10DDI_HBLENDSTATE) { (void)0; }
static SIZE_T APIENTRY _wm_stub_76_pfnCalcPrivateDepthStencilStateSize(D3D10DDI_HDEVICE, CONST D3D10_DDI_DEPTH_STENCIL_DESC*) { return 0; }
static VOID APIENTRY _wm_stub_77_pfnCreateDepthStencilState(D3D10DDI_HDEVICE, CONST D3D10_DDI_DEPTH_STENCIL_DESC*, D3D10DDI_HDEPTHSTENCILSTATE, D3D10DDI_HRTDEPTHSTENCILSTATE) { (void)0; }
static VOID APIENTRY _wm_stub_78_pfnDestroyDepthStencilState(D3D10DDI_HDEVICE, D3D10DDI_HDEPTHSTENCILSTATE) { (void)0; }
static SIZE_T APIENTRY _wm_stub_79_pfnCalcPrivateRasterizerStateSize(D3D10DDI_HDEVICE, CONST D3D10_DDI_RASTERIZER_DESC*) { return 0; }
static VOID APIENTRY _wm_stub_80_pfnCreateRasterizerState(D3D10DDI_HDEVICE, CONST D3D10_DDI_RASTERIZER_DESC*, D3D10DDI_HRASTERIZERSTATE, D3D10DDI_HRTRASTERIZERSTATE) { (void)0; }
static VOID APIENTRY _wm_stub_81_pfnDestroyRasterizerState(D3D10DDI_HDEVICE, D3D10DDI_HRASTERIZERSTATE) { (void)0; }
static SIZE_T APIENTRY _wm_stub_82_pfnCalcPrivateShaderSize(D3D10DDI_HDEVICE, CONST UINT* pShaderCode, CONST D3D10DDIARG_STAGE_IO_SIGNATURES*) { return 0; }
static VOID APIENTRY _wm_stub_83_pfnCreateVertexShader(D3D10DDI_HDEVICE, CONST UINT* pShaderCode, D3D10DDI_HSHADER, D3D10DDI_HRTSHADER, CONST D3D10DDIARG_STAGE_IO_SIGNATURES*) { (void)0; }
static VOID APIENTRY _wm_stub_84_pfnCreateGeometryShader(D3D10DDI_HDEVICE, CONST UINT* pShaderCode, D3D10DDI_HSHADER, D3D10DDI_HRTSHADER, CONST D3D10DDIARG_STAGE_IO_SIGNATURES*) { (void)0; }
static VOID APIENTRY _wm_stub_85_pfnCreatePixelShader(D3D10DDI_HDEVICE, CONST UINT* pShaderCode, D3D10DDI_HSHADER, D3D10DDI_HRTSHADER, CONST D3D10DDIARG_STAGE_IO_SIGNATURES*) { (void)0; }
static SIZE_T APIENTRY _wm_stub_86_pfnCalcPrivateGeometryShaderWithStreamOutput(D3D10DDI_HDEVICE, CONST D3D11DDIARG_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT*, CONST D3D10DDIARG_STAGE_IO_SIGNATURES*) { return 0; }
static VOID APIENTRY _wm_stub_87_pfnCreateGeometryShaderWithStreamOutput(D3D10DDI_HDEVICE, CONST D3D11DDIARG_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT*, D3D10DDI_HSHADER, D3D10DDI_HRTSHADER, CONST D3D10DDIARG_STAGE_IO_SIGNATURES*) { (void)0; }
static VOID APIENTRY _wm_stub_88_pfnDestroyShader(D3D10DDI_HDEVICE, D3D10DDI_HSHADER) { (void)0; }
static SIZE_T APIENTRY _wm_stub_89_pfnCalcPrivateSamplerSize(D3D10DDI_HDEVICE, CONST D3D10_DDI_SAMPLER_DESC*) { return 0; }
static VOID APIENTRY _wm_stub_90_pfnCreateSampler(D3D10DDI_HDEVICE, CONST D3D10_DDI_SAMPLER_DESC*, D3D10DDI_HSAMPLER, D3D10DDI_HRTSAMPLER) { (void)0; }
static VOID APIENTRY _wm_stub_91_pfnDestroySampler(D3D10DDI_HDEVICE, D3D10DDI_HSAMPLER) { (void)0; }
static SIZE_T APIENTRY _wm_stub_92_pfnCalcPrivateQuerySize(D3D10DDI_HDEVICE, CONST D3D10DDIARG_CREATEQUERY*) { return 0; }
static VOID APIENTRY _wm_stub_93_pfnCreateQuery(D3D10DDI_HDEVICE, CONST D3D10DDIARG_CREATEQUERY*, D3D10DDI_HQUERY, D3D10DDI_HRTQUERY) { (void)0; }
static VOID APIENTRY _wm_stub_94_pfnDestroyQuery(D3D10DDI_HDEVICE, D3D10DDI_HQUERY) { (void)0; }
static VOID APIENTRY _wm_stub_95_pfnCheckFormatSupport(D3D10DDI_HDEVICE, DXGI_FORMAT, UINT*) { (void)0; }
static VOID APIENTRY _wm_stub_96_pfnCheckMultisampleQualityLevels(D3D10DDI_HDEVICE, DXGI_FORMAT, UINT, UINT*) { (void)0; }
static VOID APIENTRY _wm_stub_97_pfnCheckCounterInfo(D3D10DDI_HDEVICE, D3D10DDI_COUNTER_INFO*) { (void)0; }
static VOID APIENTRY _wm_stub_98_pfnCheckCounter(D3D10DDI_HDEVICE, D3D10DDI_QUERY, D3D10DDI_COUNTER_TYPE*, UINT*, LPSTR, UINT* pNameLength, LPSTR, UINT* pUnitsLength, LPSTR, UINT* pDescriptionLength) { (void)0; }
static VOID APIENTRY _wm_stub_99_pfnDestroyDevice(D3D10DDI_HDEVICE) { (void)0; }
static VOID APIENTRY _wm_stub_100_pfnSetTextFilterSize(D3D10DDI_HDEVICE, UINT, UINT) { (void)0; }
static VOID APIENTRY _wm_stub_101_pfnResourceConvert(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, D3D10DDI_HRESOURCE) { (void)0; }
static VOID APIENTRY _wm_stub_102_pfnResourceConvertRegion(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT, UINT, UINT, UINT, D3D10DDI_HRESOURCE, UINT, CONST D3D10_DDI_BOX*) { (void)0; }
static VOID APIENTRY _wm_stub_103_pfnDrawIndexedInstancedIndirect(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT) { (void)0; }
static VOID APIENTRY _wm_stub_104_pfnDrawInstancedIndirect(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT) { (void)0; }
static VOID APIENTRY _wm_stub_105_pfnCommandListExecute(D3D10DDI_HDEVICE, D3D11DDI_HCOMMANDLIST) { (void)0; }
static VOID APIENTRY _wm_stub_106_pfnHsSetShaderResources(D3D10DDI_HDEVICE, UINT StartSlot, UINT NumViews, CONST D3D10DDI_HSHADERRESOURCEVIEW*) { (void)0; }
static VOID APIENTRY _wm_stub_107_pfnHsSetShader(D3D10DDI_HDEVICE, D3D10DDI_HSHADER) { (void)0; }
static VOID APIENTRY _wm_stub_108_pfnHsSetSamplers(D3D10DDI_HDEVICE, UINT StartSlot, UINT NumSamplers, CONST D3D10DDI_HSAMPLER*) { (void)0; }
static VOID APIENTRY _wm_stub_109_pfnHsSetConstantBuffers(D3D10DDI_HDEVICE, UINT StartSlot, UINT NumBuffers, CONST D3D10DDI_HRESOURCE*) { (void)0; }
static VOID APIENTRY _wm_stub_110_pfnDsSetShaderResources(D3D10DDI_HDEVICE, UINT StartSlot, UINT NumViews, CONST D3D10DDI_HSHADERRESOURCEVIEW*) { (void)0; }
static VOID APIENTRY _wm_stub_111_pfnDsSetShader(D3D10DDI_HDEVICE, D3D10DDI_HSHADER) { (void)0; }
static VOID APIENTRY _wm_stub_112_pfnDsSetSamplers(D3D10DDI_HDEVICE, UINT StartSlot, UINT NumSamplers, CONST D3D10DDI_HSAMPLER*) { (void)0; }
static VOID APIENTRY _wm_stub_113_pfnDsSetConstantBuffers(D3D10DDI_HDEVICE, UINT StartSlot, UINT NumBuffers, CONST D3D10DDI_HRESOURCE*) { (void)0; }
static VOID APIENTRY _wm_stub_114_pfnCreateHullShader(D3D10DDI_HDEVICE, CONST UINT* pShaderCode, D3D10DDI_HSHADER, D3D10DDI_HRTSHADER, CONST D3D11DDIARG_TESSELLATION_IO_SIGNATURES*) { (void)0; }
static VOID APIENTRY _wm_stub_115_pfnCreateDomainShader(D3D10DDI_HDEVICE, CONST UINT* pShaderCode, D3D10DDI_HSHADER, D3D10DDI_HRTSHADER, CONST D3D11DDIARG_TESSELLATION_IO_SIGNATURES*) { (void)0; }
static VOID APIENTRY _wm_stub_116_pfnCheckDeferredContextHandleSizes(D3D10DDI_HDEVICE, UINT* pHSizes, D3D11DDI_HANDLESIZE*) { (void)0; }
static SIZE_T APIENTRY _wm_stub_117_pfnCalcDeferredContextHandleSize(D3D10DDI_HDEVICE, D3D11DDI_HANDLETYPE, VOID*) { return 0; }
static SIZE_T APIENTRY _wm_stub_118_pfnCalcPrivateDeferredContextSize(D3D10DDI_HDEVICE, CONST D3D11DDIARG_CALCPRIVATEDEFERREDCONTEXTSIZE*) { return 0; }
static VOID APIENTRY _wm_stub_119_pfnCreateDeferredContext(D3D10DDI_HDEVICE, CONST D3D11DDIARG_CREATEDEFERREDCONTEXT*) { (void)0; }
static VOID APIENTRY _wm_stub_120_pfnAbandonCommandList(D3D10DDI_HDEVICE) { (void)0; }
static SIZE_T APIENTRY _wm_stub_121_pfnCalcPrivateCommandListSize(D3D10DDI_HDEVICE, CONST D3D11DDIARG_CREATECOMMANDLIST*) { return 0; }
static VOID APIENTRY _wm_stub_122_pfnCreateCommandList(D3D10DDI_HDEVICE, CONST D3D11DDIARG_CREATECOMMANDLIST*, D3D11DDI_HCOMMANDLIST, D3D11DDI_HRTCOMMANDLIST) { (void)0; }
static VOID APIENTRY _wm_stub_123_pfnDestroyCommandList(D3D10DDI_HDEVICE, D3D11DDI_HCOMMANDLIST) { (void)0; }
static SIZE_T APIENTRY _wm_stub_124_pfnCalcPrivateTessellationShaderSize(D3D10DDI_HDEVICE, CONST UINT* pShaderCode, CONST D3D11DDIARG_TESSELLATION_IO_SIGNATURES*) { return 0; }
static VOID APIENTRY _wm_stub_125_pfnPsSetShaderWithIfaces(D3D10DDI_HDEVICE, D3D10DDI_HSHADER, UINT NumClassInstances, CONST UINT*, CONST D3D11DDIARG_POINTERDATA*) { (void)0; }
static VOID APIENTRY _wm_stub_126_pfnVsSetShaderWithIfaces(D3D10DDI_HDEVICE, D3D10DDI_HSHADER, UINT NumClassInstances, CONST UINT*, CONST D3D11DDIARG_POINTERDATA*) { (void)0; }
static VOID APIENTRY _wm_stub_127_pfnGsSetShaderWithIfaces(D3D10DDI_HDEVICE, D3D10DDI_HSHADER, UINT NumClassInstances, CONST UINT*, CONST D3D11DDIARG_POINTERDATA*) { (void)0; }
static VOID APIENTRY _wm_stub_128_pfnHsSetShaderWithIfaces(D3D10DDI_HDEVICE, D3D10DDI_HSHADER, UINT NumClassInstances, CONST UINT*, CONST D3D11DDIARG_POINTERDATA*) { (void)0; }
static VOID APIENTRY _wm_stub_129_pfnDsSetShaderWithIfaces(D3D10DDI_HDEVICE, D3D10DDI_HSHADER, UINT NumClassInstances, CONST UINT*, CONST D3D11DDIARG_POINTERDATA*) { (void)0; }
static VOID APIENTRY _wm_stub_130_pfnCsSetShaderWithIfaces(D3D10DDI_HDEVICE, D3D10DDI_HSHADER, UINT NumClassInstances, CONST UINT*, CONST D3D11DDIARG_POINTERDATA*) { (void)0; }
static VOID APIENTRY _wm_stub_131_pfnCreateComputeShader(D3D10DDI_HDEVICE, CONST UINT* pShaderCode, D3D10DDI_HSHADER, D3D10DDI_HRTSHADER) { (void)0; }
static VOID APIENTRY _wm_stub_132_pfnCsSetShader(D3D10DDI_HDEVICE, D3D10DDI_HSHADER) { (void)0; }
static VOID APIENTRY _wm_stub_133_pfnCsSetShaderResources(D3D10DDI_HDEVICE, UINT StartSlot, UINT NumViews, CONST D3D10DDI_HSHADERRESOURCEVIEW*) { (void)0; }
static VOID APIENTRY _wm_stub_134_pfnCsSetSamplers(D3D10DDI_HDEVICE, UINT StartSlot, UINT NumSamplers, CONST D3D10DDI_HSAMPLER*) { (void)0; }
static VOID APIENTRY _wm_stub_135_pfnCsSetConstantBuffers(D3D10DDI_HDEVICE, UINT StartSlot, UINT NumBuffers, CONST D3D10DDI_HRESOURCE*) { (void)0; }
static SIZE_T APIENTRY _wm_stub_136_pfnCalcPrivateUnorderedAccessViewSize(D3D10DDI_HDEVICE, CONST D3D11DDIARG_CREATEUNORDEREDACCESSVIEW*) { return 0; }
static VOID APIENTRY _wm_stub_137_pfnCreateUnorderedAccessView(D3D10DDI_HDEVICE, CONST D3D11DDIARG_CREATEUNORDEREDACCESSVIEW*, D3D11DDI_HUNORDEREDACCESSVIEW, D3D11DDI_HRTUNORDEREDACCESSVIEW) { (void)0; }
static VOID APIENTRY _wm_stub_138_pfnDestroyUnorderedAccessView(D3D10DDI_HDEVICE, D3D11DDI_HUNORDEREDACCESSVIEW) { (void)0; }
static VOID APIENTRY _wm_stub_139_pfnClearUnorderedAccessViewUint(D3D10DDI_HDEVICE, D3D11DDI_HUNORDEREDACCESSVIEW, CONST UINT[4]) { (void)0; }
static VOID APIENTRY _wm_stub_140_pfnClearUnorderedAccessViewFloat(D3D10DDI_HDEVICE, D3D11DDI_HUNORDEREDACCESSVIEW, CONST FLOAT[4]) { (void)0; }
static VOID APIENTRY _wm_stub_141_pfnCsSetUnorderedAccessViews(D3D10DDI_HDEVICE, UINT StartSlot, UINT NumViews, CONST D3D11DDI_HUNORDEREDACCESSVIEW*, CONST UINT*) { (void)0; }
static VOID APIENTRY _wm_stub_142_pfnDispatch(D3D10DDI_HDEVICE, UINT, UINT, UINT) { (void)0; }
static VOID APIENTRY _wm_stub_143_pfnDispatchIndirect(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT) { (void)0; }
static VOID APIENTRY _wm_stub_144_pfnSetResourceMinLOD(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, FLOAT) { (void)0; }
static VOID APIENTRY _wm_stub_145_pfnCopyStructureCount(D3D10DDI_HDEVICE, D3D10DDI_HRESOURCE, UINT, D3D11DDI_HUNORDEREDACCESSVIEW) { (void)0; }
static VOID APIENTRY _wm_stub_146_pfnRecycleCommandList(D3D10DDI_HDEVICE /*DC-only*/, D3D11DDI_HCOMMANDLIST /* IC handle */) { (void)0; }
static HRESULT APIENTRY _wm_stub_147_pfnRecycleCreateCommandList(D3D10DDI_HDEVICE, CONST D3D11DDIARG_CREATECOMMANDLIST*, D3D11DDI_HCOMMANDLIST, D3D11DDI_HRTCOMMANDLIST) { return E_NOTIMPL; }
static HRESULT APIENTRY _wm_stub_148_pfnRecycleCreateDeferredContext(D3D10DDI_HDEVICE, CONST D3D11DDIARG_CREATEDEFERREDCONTEXT*) { return E_NOTIMPL; }
static VOID APIENTRY _wm_stub_149_pfnRecycleDestroyCommandList(D3D10DDI_HDEVICE, D3D11DDI_HCOMMANDLIST) { (void)0; }

extern "C" void WinMaliUmdFillD3d11DeviceFuncs(D3D11DDI_DEVICEFUNCS *df) {
  if (!df) return;
  memset(df, 0, sizeof(*df));
  df->pfnDefaultConstantBufferUpdateSubresourceUP = _wm_stub_0_pfnDefaultConstantBufferUpdateSubresourceUP;
  df->pfnVsSetConstantBuffers = _wm_stub_1_pfnVsSetConstantBuffers;
  df->pfnPsSetShaderResources = _wm_stub_2_pfnPsSetShaderResources;
  df->pfnPsSetShader = _wm_stub_3_pfnPsSetShader;
  df->pfnPsSetSamplers = _wm_stub_4_pfnPsSetSamplers;
  df->pfnVsSetShader = _wm_stub_5_pfnVsSetShader;
  df->pfnDrawIndexed = _wm_stub_6_pfnDrawIndexed;
  df->pfnDraw = _wm_stub_7_pfnDraw;
  df->pfnDynamicIABufferMapNoOverwrite = _wm_stub_8_pfnDynamicIABufferMapNoOverwrite;
  df->pfnDynamicIABufferUnmap = _wm_stub_9_pfnDynamicIABufferUnmap;
  df->pfnDynamicConstantBufferMapDiscard = _wm_stub_10_pfnDynamicConstantBufferMapDiscard;
  df->pfnDynamicIABufferMapDiscard = _wm_stub_11_pfnDynamicIABufferMapDiscard;
  df->pfnDynamicConstantBufferUnmap = _wm_stub_12_pfnDynamicConstantBufferUnmap;
  df->pfnPsSetConstantBuffers = _wm_stub_13_pfnPsSetConstantBuffers;
  df->pfnIaSetInputLayout = _wm_stub_14_pfnIaSetInputLayout;
  df->pfnIaSetVertexBuffers = _wm_stub_15_pfnIaSetVertexBuffers;
  df->pfnIaSetIndexBuffer = _wm_stub_16_pfnIaSetIndexBuffer;
  df->pfnDrawIndexedInstanced = _wm_stub_17_pfnDrawIndexedInstanced;
  df->pfnDrawInstanced = _wm_stub_18_pfnDrawInstanced;
  df->pfnDynamicResourceMapDiscard = _wm_stub_19_pfnDynamicResourceMapDiscard;
  df->pfnDynamicResourceUnmap = _wm_stub_20_pfnDynamicResourceUnmap;
  df->pfnGsSetConstantBuffers = _wm_stub_21_pfnGsSetConstantBuffers;
  df->pfnGsSetShader = _wm_stub_22_pfnGsSetShader;
  df->pfnIaSetTopology = _wm_stub_23_pfnIaSetTopology;
  df->pfnStagingResourceMap = _wm_stub_24_pfnStagingResourceMap;
  df->pfnStagingResourceUnmap = _wm_stub_25_pfnStagingResourceUnmap;
  df->pfnVsSetShaderResources = _wm_stub_26_pfnVsSetShaderResources;
  df->pfnVsSetSamplers = _wm_stub_27_pfnVsSetSamplers;
  df->pfnGsSetShaderResources = _wm_stub_28_pfnGsSetShaderResources;
  df->pfnGsSetSamplers = _wm_stub_29_pfnGsSetSamplers;
  df->pfnSetRenderTargets = _wm_stub_30_pfnSetRenderTargets;
  df->pfnShaderResourceViewReadAfterWriteHazard = _wm_stub_31_pfnShaderResourceViewReadAfterWriteHazard;
  df->pfnResourceReadAfterWriteHazard = _wm_stub_32_pfnResourceReadAfterWriteHazard;
  df->pfnSetBlendState = _wm_stub_33_pfnSetBlendState;
  df->pfnSetDepthStencilState = _wm_stub_34_pfnSetDepthStencilState;
  df->pfnSetRasterizerState = _wm_stub_35_pfnSetRasterizerState;
  df->pfnQueryEnd = _wm_stub_36_pfnQueryEnd;
  df->pfnQueryBegin = _wm_stub_37_pfnQueryBegin;
  df->pfnResourceCopyRegion = _wm_stub_38_pfnResourceCopyRegion;
  df->pfnResourceUpdateSubresourceUP = _wm_stub_39_pfnResourceUpdateSubresourceUP;
  df->pfnSoSetTargets = _wm_stub_40_pfnSoSetTargets;
  df->pfnDrawAuto = _wm_stub_41_pfnDrawAuto;
  df->pfnSetViewports = _wm_stub_42_pfnSetViewports;
  df->pfnSetScissorRects = _wm_stub_43_pfnSetScissorRects;
  df->pfnClearRenderTargetView = _wm_stub_44_pfnClearRenderTargetView;
  df->pfnClearDepthStencilView = _wm_stub_45_pfnClearDepthStencilView;
  df->pfnSetPredication = _wm_stub_46_pfnSetPredication;
  df->pfnQueryGetData = _wm_stub_47_pfnQueryGetData;
  df->pfnFlush = _wm_stub_48_pfnFlush;
  df->pfnGenMips = _wm_stub_49_pfnGenMips;
  df->pfnResourceCopy = _wm_stub_50_pfnResourceCopy;
  df->pfnResourceResolveSubresource = _wm_stub_51_pfnResourceResolveSubresource;
  df->pfnResourceMap = _wm_stub_52_pfnResourceMap;
  df->pfnResourceUnmap = _wm_stub_53_pfnResourceUnmap;
  df->pfnResourceIsStagingBusy = _wm_stub_54_pfnResourceIsStagingBusy;
  df->pfnRelocateDeviceFuncs = _wm_stub_55_pfnRelocateDeviceFuncs;
  df->pfnCalcPrivateResourceSize = _wm_stub_56_pfnCalcPrivateResourceSize;
  df->pfnCalcPrivateOpenedResourceSize = _wm_stub_57_pfnCalcPrivateOpenedResourceSize;
  df->pfnCreateResource = _wm_stub_58_pfnCreateResource;
  df->pfnOpenResource = _wm_stub_59_pfnOpenResource;
  df->pfnDestroyResource = _wm_stub_60_pfnDestroyResource;
  df->pfnCalcPrivateShaderResourceViewSize = _wm_stub_61_pfnCalcPrivateShaderResourceViewSize;
  df->pfnCreateShaderResourceView = _wm_stub_62_pfnCreateShaderResourceView;
  df->pfnDestroyShaderResourceView = _wm_stub_63_pfnDestroyShaderResourceView;
  df->pfnCalcPrivateRenderTargetViewSize = _wm_stub_64_pfnCalcPrivateRenderTargetViewSize;
  df->pfnCreateRenderTargetView = _wm_stub_65_pfnCreateRenderTargetView;
  df->pfnDestroyRenderTargetView = _wm_stub_66_pfnDestroyRenderTargetView;
  df->pfnCalcPrivateDepthStencilViewSize = _wm_stub_67_pfnCalcPrivateDepthStencilViewSize;
  df->pfnCreateDepthStencilView = _wm_stub_68_pfnCreateDepthStencilView;
  df->pfnDestroyDepthStencilView = _wm_stub_69_pfnDestroyDepthStencilView;
  df->pfnCalcPrivateElementLayoutSize = _wm_stub_70_pfnCalcPrivateElementLayoutSize;
  df->pfnCreateElementLayout = _wm_stub_71_pfnCreateElementLayout;
  df->pfnDestroyElementLayout = _wm_stub_72_pfnDestroyElementLayout;
  df->pfnCalcPrivateBlendStateSize = _wm_stub_73_pfnCalcPrivateBlendStateSize;
  df->pfnCreateBlendState = _wm_stub_74_pfnCreateBlendState;
  df->pfnDestroyBlendState = _wm_stub_75_pfnDestroyBlendState;
  df->pfnCalcPrivateDepthStencilStateSize = _wm_stub_76_pfnCalcPrivateDepthStencilStateSize;
  df->pfnCreateDepthStencilState = _wm_stub_77_pfnCreateDepthStencilState;
  df->pfnDestroyDepthStencilState = _wm_stub_78_pfnDestroyDepthStencilState;
  df->pfnCalcPrivateRasterizerStateSize = _wm_stub_79_pfnCalcPrivateRasterizerStateSize;
  df->pfnCreateRasterizerState = _wm_stub_80_pfnCreateRasterizerState;
  df->pfnDestroyRasterizerState = _wm_stub_81_pfnDestroyRasterizerState;
  df->pfnCalcPrivateShaderSize = _wm_stub_82_pfnCalcPrivateShaderSize;
  df->pfnCreateVertexShader = _wm_stub_83_pfnCreateVertexShader;
  df->pfnCreateGeometryShader = _wm_stub_84_pfnCreateGeometryShader;
  df->pfnCreatePixelShader = _wm_stub_85_pfnCreatePixelShader;
  df->pfnCalcPrivateGeometryShaderWithStreamOutput = _wm_stub_86_pfnCalcPrivateGeometryShaderWithStreamOutput;
  df->pfnCreateGeometryShaderWithStreamOutput = _wm_stub_87_pfnCreateGeometryShaderWithStreamOutput;
  df->pfnDestroyShader = _wm_stub_88_pfnDestroyShader;
  df->pfnCalcPrivateSamplerSize = _wm_stub_89_pfnCalcPrivateSamplerSize;
  df->pfnCreateSampler = _wm_stub_90_pfnCreateSampler;
  df->pfnDestroySampler = _wm_stub_91_pfnDestroySampler;
  df->pfnCalcPrivateQuerySize = _wm_stub_92_pfnCalcPrivateQuerySize;
  df->pfnCreateQuery = _wm_stub_93_pfnCreateQuery;
  df->pfnDestroyQuery = _wm_stub_94_pfnDestroyQuery;
  df->pfnCheckFormatSupport = _wm_stub_95_pfnCheckFormatSupport;
  df->pfnCheckMultisampleQualityLevels = _wm_stub_96_pfnCheckMultisampleQualityLevels;
  df->pfnCheckCounterInfo = _wm_stub_97_pfnCheckCounterInfo;
  df->pfnCheckCounter = _wm_stub_98_pfnCheckCounter;
  df->pfnDestroyDevice = _wm_stub_99_pfnDestroyDevice;
  df->pfnSetTextFilterSize = _wm_stub_100_pfnSetTextFilterSize;
  df->pfnResourceConvert = _wm_stub_101_pfnResourceConvert;
  df->pfnResourceConvertRegion = _wm_stub_102_pfnResourceConvertRegion;
  df->pfnDrawIndexedInstancedIndirect = _wm_stub_103_pfnDrawIndexedInstancedIndirect;
  df->pfnDrawInstancedIndirect = _wm_stub_104_pfnDrawInstancedIndirect;
  df->pfnCommandListExecute = _wm_stub_105_pfnCommandListExecute;
  df->pfnHsSetShaderResources = _wm_stub_106_pfnHsSetShaderResources;
  df->pfnHsSetShader = _wm_stub_107_pfnHsSetShader;
  df->pfnHsSetSamplers = _wm_stub_108_pfnHsSetSamplers;
  df->pfnHsSetConstantBuffers = _wm_stub_109_pfnHsSetConstantBuffers;
  df->pfnDsSetShaderResources = _wm_stub_110_pfnDsSetShaderResources;
  df->pfnDsSetShader = _wm_stub_111_pfnDsSetShader;
  df->pfnDsSetSamplers = _wm_stub_112_pfnDsSetSamplers;
  df->pfnDsSetConstantBuffers = _wm_stub_113_pfnDsSetConstantBuffers;
  df->pfnCreateHullShader = _wm_stub_114_pfnCreateHullShader;
  df->pfnCreateDomainShader = _wm_stub_115_pfnCreateDomainShader;
  df->pfnCheckDeferredContextHandleSizes = _wm_stub_116_pfnCheckDeferredContextHandleSizes;
  df->pfnCalcDeferredContextHandleSize = _wm_stub_117_pfnCalcDeferredContextHandleSize;
  df->pfnCalcPrivateDeferredContextSize = _wm_stub_118_pfnCalcPrivateDeferredContextSize;
  df->pfnCreateDeferredContext = _wm_stub_119_pfnCreateDeferredContext;
  df->pfnAbandonCommandList = _wm_stub_120_pfnAbandonCommandList;
  df->pfnCalcPrivateCommandListSize = _wm_stub_121_pfnCalcPrivateCommandListSize;
  df->pfnCreateCommandList = _wm_stub_122_pfnCreateCommandList;
  df->pfnDestroyCommandList = _wm_stub_123_pfnDestroyCommandList;
  df->pfnCalcPrivateTessellationShaderSize = _wm_stub_124_pfnCalcPrivateTessellationShaderSize;
  df->pfnPsSetShaderWithIfaces = _wm_stub_125_pfnPsSetShaderWithIfaces;
  df->pfnVsSetShaderWithIfaces = _wm_stub_126_pfnVsSetShaderWithIfaces;
  df->pfnGsSetShaderWithIfaces = _wm_stub_127_pfnGsSetShaderWithIfaces;
  df->pfnHsSetShaderWithIfaces = _wm_stub_128_pfnHsSetShaderWithIfaces;
  df->pfnDsSetShaderWithIfaces = _wm_stub_129_pfnDsSetShaderWithIfaces;
  df->pfnCsSetShaderWithIfaces = _wm_stub_130_pfnCsSetShaderWithIfaces;
  df->pfnCreateComputeShader = _wm_stub_131_pfnCreateComputeShader;
  df->pfnCsSetShader = _wm_stub_132_pfnCsSetShader;
  df->pfnCsSetShaderResources = _wm_stub_133_pfnCsSetShaderResources;
  df->pfnCsSetSamplers = _wm_stub_134_pfnCsSetSamplers;
  df->pfnCsSetConstantBuffers = _wm_stub_135_pfnCsSetConstantBuffers;
  df->pfnCalcPrivateUnorderedAccessViewSize = _wm_stub_136_pfnCalcPrivateUnorderedAccessViewSize;
  df->pfnCreateUnorderedAccessView = _wm_stub_137_pfnCreateUnorderedAccessView;
  df->pfnDestroyUnorderedAccessView = _wm_stub_138_pfnDestroyUnorderedAccessView;
  df->pfnClearUnorderedAccessViewUint = _wm_stub_139_pfnClearUnorderedAccessViewUint;
  df->pfnClearUnorderedAccessViewFloat = _wm_stub_140_pfnClearUnorderedAccessViewFloat;
  df->pfnCsSetUnorderedAccessViews = _wm_stub_141_pfnCsSetUnorderedAccessViews;
  df->pfnDispatch = _wm_stub_142_pfnDispatch;
  df->pfnDispatchIndirect = _wm_stub_143_pfnDispatchIndirect;
  df->pfnSetResourceMinLOD = _wm_stub_144_pfnSetResourceMinLOD;
  df->pfnCopyStructureCount = _wm_stub_145_pfnCopyStructureCount;
  df->pfnRecycleCommandList = _wm_stub_146_pfnRecycleCommandList;
  df->pfnRecycleCreateCommandList = _wm_stub_147_pfnRecycleCreateCommandList;
  df->pfnRecycleCreateDeferredContext = _wm_stub_148_pfnRecycleCreateDeferredContext;
  df->pfnRecycleDestroyCommandList = _wm_stub_149_pfnRecycleDestroyCommandList;
}
