# Generate UMD/wm_d3d11_devstubs.c — C stubs for D3D11DDI_DEVICEFUNCS (d3d10umddi.h).
import os
import re
from pathlib import Path


def iter_pfn_typedef_blocks(text: str):
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        ln = lines[i]
        if "typedef" in ln and "APIENTRY" in ln and "PFND3D" in ln:
            buf = [ln]
            while i < len(lines) and not lines[i].strip().endswith(");"):
                i += 1
                buf.append(lines[i])
            yield "\n".join(buf)
        i += 1


def parse_typedefs(text: str) -> dict:
    out = {}
    for block in iter_pfn_typedef_blocks(text):
        m = re.search(
            r"typedef\s+(\w+)\s*\(\s*APIENTRY\s*\*\s*(PFND3D[A-Z0-9_]+)\s*\)\s*\(",
            block,
            re.S,
        )
        if not m:
            continue
        ret, pfn = m.group(1), m.group(2)
        start = m.end()
        end = block.rindex(")")
        args = block[start:end]
        out[pfn] = (ret, args)
    return out


def extract_dev11_fields(text: str) -> list:
    lines = text.splitlines()
    start = None
    for i, line in enumerate(lines):
        if "typedef struct D3D11DDI_DEVICEFUNCS" in line:
            for j in range(i, min(i + 6, len(lines))):
                if "{" in lines[j]:
                    start = j
                    break
            break
    if start is None:
        raise SystemExit("D3D11DDI_DEVICEFUNCS typedef not found")
    fields = []
    in_psgp = False
    for k in range(start, len(lines)):
        line = lines[k]
        if "#ifdef D3D10PSGP" in line:
            in_psgp = True
            continue
        if in_psgp and "#endif" in line and "D3D10PSGP" in line:
            in_psgp = False
            continue
        if in_psgp:
            continue
        mo = re.search(r"(PFND3D[0-9A-Z_]+)\s+(\w+)\s*;", line)
        if mo:
            fields.append((mo.group(1), mo.group(2)))
        if "} D3D11DDI_DEVICEFUNCS" in line:
            break
    return fields


def strip_sal(arglist: str) -> str:
    s = arglist
    s = re.sub(r"//[^\n]*", "", s)
    s = re.sub(r"_Inout_updates_bytes_opt_[^)]*\)\s*", "", s)
    s = re.sub(r"_In_reads_bytes_opt_[^)]*\)\s*", "", s)
    s = re.sub(r"_In_reads_bytes_[^)]*\)\s*", "", s)
    s = re.sub(r"_In_reads_[^)]*\)\s*", "", s)
    s = re.sub(r"_In_range_[^)]*\)\s*", "", s)
    s = re.sub(r"_In_opt_[^)]*\)\s*", "", s)
    s = re.sub(r"\b_Inout_opt_\b\s*", "", s)
    s = re.sub(r"\b_Inout_\b\s*", "", s)
    s = re.sub(r"\b_In_opt_\b\s*", "", s)
    s = re.sub(r"_Outptr_[^)]*\)\s*", "", s)
    s = re.sub(r"_Out_writes_[^)]*\)\s*", "", s)
    s = re.sub(r"_Out_[^)]*\)\s*", "", s)
    s = re.sub(r"\b_Out_\b\s*", "", s)
    s = re.sub(r"\b_In_\b\s*", "", s)
    s = re.sub(r"\s+", " ", s)
    return s.strip()


def resolve_sdk_header() -> Path:
    base = os.environ.get("WindowsSdkDir", r"C:\Program Files (x86)\Windows Kits\10")
    inc = Path(base) / "Include"
    if not inc.is_dir():
        raise SystemExit(f"Windows SDK Include not found: {inc}")
    vers = sorted([p for p in inc.iterdir() if p.is_dir() and p.name.startswith("10.")], reverse=True)
    for v in vers:
        cand = v / "um" / "d3d10umddi.h"
        if cand.is_file():
            return cand
    raise SystemExit(f"No d3d10umddi.h under {inc}")


def main() -> None:
    sdk = resolve_sdk_header()
    text = sdk.read_text(encoding="utf-8", errors="ignore")
    typedef_blocks = parse_typedefs(text)
    fields = extract_dev11_fields(text)

    out = []
    out.append("// AUTO-GENERATED by Tools/gen_d3d11_devstubs.py — do not edit by hand.")
    out.append("// Compiled as C++ (MSVC C disallows unnamed parameters in stub definitions).")
    out.append(f"// Source SDK header: {sdk}")
    out.append('#include "WinMaliUmd.h"')
    out.append("#include <cstring>")
    out.append("")
    for idx, (pfn, field) in enumerate(fields):
        if pfn not in typedef_blocks:
            raise SystemExit(f"Missing typedef for {pfn} ({field})")
        ret, args = typedef_blocks[pfn]
        stub = f"_wm_stub_{idx}_{field}"
        arglist = strip_sal(args)
        ret = ret.strip()
        if ret == "VOID":
            out.append(f"static {ret} APIENTRY {stub}({arglist}) {{ (void)0; }}")
        elif ret == "SIZE_T":
            out.append(f"static {ret} APIENTRY {stub}({arglist}) {{ return 0; }}")
        elif ret == "HRESULT":
            out.append(f"static {ret} APIENTRY {stub}({arglist}) {{ return E_NOTIMPL; }}")
        else:
            out.append(f"static {ret} APIENTRY {stub}({arglist}) {{ return 0; }}")

    out.append("")
    out.append(
        'extern "C" void WinMaliUmdFillD3d11DeviceFuncs(D3D11DDI_DEVICEFUNCS *df) {'
    )
    out.append("  if (!df) return;")
    out.append("  memset(df, 0, sizeof(*df));")
    for idx, (_, field) in enumerate(fields):
        stub = f"_wm_stub_{idx}_{field}"
        out.append(f"  df->{field} = {stub};")
    out.append("}")

    dest = Path(__file__).resolve().parents[1] / "UMD" / "wm_d3d11_devstubs.cpp"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"Wrote {dest} ({len(fields)} fields, {dest.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
